import type { EngineTrustgap, EngineTriage } from './snapshot';
import { text } from './snapshot';

export function RawEvidence({ payload }: { payload: unknown }) {
  return <details className="panel evidence-panel"><summary>Raw court JSON · as reported</summary><pre className="method-summary">{JSON.stringify(payload, null, 2)}</pre></details>;
}
const score = (value: number | null) => value === null ? 'Not recorded' : `${value}%`;
export function EngineTrustgapView({ data }: { data: EngineTrustgap }) {
  const entries = data.mutants ?? data.survivors;
  return <><div className="notice" role="status"><strong>Engine mutation ledger · reported values.</strong> Scores are percentage points (0–100) as emitted by the engine, not dashboard fractions. Ledger consistency and attribution have not been independently verified. Missing metrics are not zero or a pass.</div><div className="metrics three">{([['CLAIMED COVERAGE', data.claimedCoverage], ['HONEST MUTATION SCORE', data.honestMutationScore], ['TRUST GAP', data.trustGap]] as const).map(([label, value]) => <div className="metric" key={label}><span className="metric-label">{label}</span><strong>{label === 'TRUST GAP' && value !== null ? `${value} pp` : score(value)}</strong><small>Engine reported · {label === 'TRUST GAP' ? 'percentage points' : '0–100 percent'}</small></div>)}</div><div className="split-layout"><article className="panel"><h3>Attribution &amp; totals</h3><p>Attribution: {data.attribution ?? 'Not recorded'}</p>{data.attributionNote && <p>{data.attributionNote}</p>}{data.totals ? <dl className="field-list">{Object.entries(data.totals).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{text(value)}</dd></div>)}</dl> : <p>No totals supplied.</p>}{data.summary && <p className="method-summary">{data.summary}</p>}</article><article className="panel"><h3>Reported dishonest tests</h3>{data.dishonestTests.length ? <ul className="test-list">{data.dishonestTests.map((entry, i) => <li key={i}><span className="test-alert" aria-hidden="true">!</span><div><code>{entry.testName || entry.testId}</code>{entry.testName && <small> ID: {entry.testId}</small>}<small>Surviving mutants: {entry.survivedMutants.length ? entry.survivedMutants.map(text).join(', ') : 'None listed'}</small></div></li>)}</ul> : <p className="muted">No tests named in this ledger. Survivors may be unattributed; this does not establish that tests are honest.</p>}</article></div><article className="panel"><h3>Mutation evidence</h3>{entries?.length ? <div className="mutation-list">{entries.map((entry, i) => <div key={i} className="mutation-item"><code>{text(entry)}</code></div>)}</div> : <p className="muted">No individual mutant entries supplied. Do not infer that there were no survivors.</p>}{data.itLedger && <p>Additional per-test ledger: {data.itLedger.length} entries (see raw JSON; not reconciled with these totals).</p>}</article><RawEvidence payload={data} /></>;
}
export function EngineTriageView({ data }: { data: EngineTriage }) {
  const fields = (value: Record<string, unknown> | null) => value && Object.keys(value).length ? <dl className="field-list">{Object.entries(value).map(([key, val]) => <div key={key}><dt>{key}</dt><dd>{text(val)}</dd></div>)}</dl> : <p className="muted">Not recorded. No clearance can be inferred.</p>;
  return <><div className="notice" role="status"><strong>Engine triage · candidate, not confirmed cause.</strong> Correlation and timestamps are producer-reported; verify against source fixtures.</div><div className="metrics three"><div className="metric"><span className="metric-label">INCIDENT WINDOW</span><strong>{data.incidentWindow}</strong><small>As reported</small></div><div className="metric"><span className="metric-label">TRIAGE SIGNALS</span><strong>{data.evidence.length}</strong><small>Reported warning/error lines</small></div><div className="metric"><span className="metric-label">CLEARED DEPLOYS</span><strong>{data.clearedDeploys.length}</strong><small>As reported</small></div></div><div className="war-grid"><article className="panel"><h3>Suspect deploy · unconfirmed</h3>{fields(data.suspect)}</article><article className="panel"><h3>Breaker snapshot</h3>{fields(data.breakerSnapshot)}</article></div><article className="panel"><h3>Reported signals</h3>{data.evidence.length ? <div className="log-list">{data.evidence.map((line, i) => <div className="log-entry" key={i}><span className="log-level">{text(line.level ?? 'signal')}</span><span className="mono">{text(line.t ?? 'Time unknown')}</span><span>{text(line.msg ?? line.message ?? line)}</span>{line.spec != null && <code>{text(line.spec)}</code>}</div>)}</div> : <p>No signals supplied; this does not prove the incident was safe.</p>}<h3>Cleared deploys · as reported</h3>{data.clearedDeploys.length ? <ul className="simple-list">{data.clearedDeploys.map((entry, i) => <li key={i}>{text(entry)}</li>)}</ul> : <p>None recorded.</p>}{data.rule !== null && <><h3>Derived rule · as reported</h3><p className="rule">{data.rule}</p></>}</article><RawEvidence payload={data} /></>;
}
